service: aws-sg-stepfunctions-demo
provider:
  name: aws
  runtime: nodejs12.x
  region: ap-southeast-1


functions:
    - ${file(./aws-resources/function-definitions.yml)}
stepFunctions:
  validate: true
  stateMachines:
    ExpressWorkflowDemo:
      ${file(./aws-resources/stepfunctions-definition.yml)}

resources:
  - ${file(./aws-resources/aws-cloudwatch.yml)}

plugins:
  - serverless-step-functions
  - serverless-pseudo-parameters

